### ISSUE TITLE
Readme - Plugin Folder Location

### ISSUE THREAD

**Issue by Dennis-Eldridge** [dimven/NavisPythonShell#1]
In the readme the plugin folder is under %programdata% not %appdata%.

**Comment by pabloderen** [comment]
But the readme says %appdata%?

**Comment by dimven** [comment]
Navisworks has multiple load paths for plugins:
http://adndevblog.typepad.com/aec/2013/05/navisworks-2014-api-new-feature-one-more-path-to-load-plugin.html

The advantage of choosing the user folder is that you don't have to deal with raised privileges. The disadvantage is that if a PC has multiple accounts, then other accounts will not load the plugin.
