### ISSUE TITLE
Compile broken: missing DLLs

### ISSUE THREAD

**Issue by sanzoghenzo** [dimven/NavisPythonShell#2]
Hi,
I'm using navisworks Manage 2017 and had some trouble building the plugin from sources.
You forgot to copy the RequiredLibraries folder from RevitPythonShell, or at least the two assemblies:
- WPG.dll
- System.Windows.Controls.WpfPropertyGrid.dll

I don't know where they come from or if it's possible to add them via NuGet.
With these two references in place I was able to build and run the plugin in NV 2017.

**Comment by dimven** [comment]
Thanks for pointing that out. I think that RPS got them originally from some now defunct projects at https://www.codeproject.com/

I've added the folder with all required external assemblies.
