### ISSUE TITLE
No Ribbon Buttons shown in Navisworks

### ISSUE THREAD

**Issue by tangrui1992** [dimven/NavisPythonShell#3]
Hi everyone,

I tried installing the Navisworks Python shell by extracting the release zip file to the %APPDATA%\Autodesk Navisworks Manage 2016\Plugins location, but when I run the Navisworks software I don't see any buttons in the ribbon so I can't start the python shell. I know it's definitely loaded into Navisworks because when I tried to delete the folder when Navisworks is running, it won't let me delete it. So my question is, how do I get the python shell buttons showing? Thanks a lot!

Rui

**Comment by tangrui1992** [comment]
Problem Solved:
Need to compile the solution from the source file, add references from the "RevitPythonShell" folder (which is actually for this NavisPythonShell project), build the solution in Visual Studio, and copy the build folder to Plugins folder, change the Build Folder name to "RevitPythonShell" and then run the Navisworks.

Now I have it. Issue closed.

**Comment by tpjma** [comment]
> Problem Solved:
> Need to compile the solution from the source file, add references from the "RevitPythonShell" folder (which is actually for this NavisPythonShell project), build the solution in Visual Studio, and copy the build folder to Plugins folder, change the Build Folder name to "RevitPythonShell" and then run the Navisworks.
> 
> Now I have it. Issue closed.

Please could the steps above be explained? Thanks.
