### ISSUE TITLE
Script Example List of properties import nwp 

### ISSUE THREAD

**Issue by ambrogomez** [dimven/NavisPythonShell#5]
Hi there,

Thank you for the NPS. It is great.

I am trying for a while to get the properties of element through NPS, however it always give me an error:
SystemError: Only valid for ModelItem in a document

I started looking to the example and I saw you were taking the properties in one of your examples.

I realised nwp is imported.

I tried to import, and totally copy and paste the example and it does not work either.

Could I please ask if I am missing something here?

Thank you very much.

**Comment by ambrogomez** [comment]
Solved.

It seems the Navis Python Wrapper was not included.

**Comment by dimven** [comment]
Yep, thanks for spotting that. I'll need to check with @eirannejad for the Navis Python Wrapper. For now you can modify the sample to get the selection like this:
https://github.com/dimven/NavisPythonShell/blob/master/Script%20Examples/listProperties.py#L1

**Comment by eirannejad** [comment]
Navis Python Wrapper is open-source. Feel free to fork and modify. I don't actually use Navisworks at the moment so kinda stopped development on it.

https://github.com/eirannejad/NavisPythonWrapper
