### ISSUE TITLE
Navisworks crashes when click on NPS

### ISSUE THREAD

**Issue by MM-SalvoDragotta** [dimven/NavisPythonShell#6]
I've recompiled in both manage 2018 and 2019 but Navisworks crashes when I try to open NPS.
Any idea why?

**Comment by dimven** [comment]
Hi,

Did you have any problems when compiling? I just made some minor cleanup of the csproject files (removed the reference to a specific version of the api dll) and had to migrate them to NET 4.7 because that's what the 2020 was targeting.

Could you please try the 2020 release and the updated installation readme on your end and see if that helps?

**Comment by MM-SalvoDragotta** [comment]
No problems when compiling. I tried the 2020 version and same story. When I click on NPS, it spins for a bit but Navisworks crashes at the end with no messages. 
I'm using Manage 2020 (64bit) version 17.0.1336.83. could there be anything preventing add-ins from running?

Also how do I change the name of the tab in the Ribbon to say "Python Shell" instead of Tool add-ins 1?

![image](https://user-images.githubusercontent.com/54158123/64656417-b2a48f00-d472-11e9-8aee-cb4886b3dcd5.png)

**Comment by dimven** [comment]
Can't imagine what would cause it. Try setting a breakpoint at the start of the `Execute` method and debugging:
![image](https://user-images.githubusercontent.com/7148394/64680385-5cd9e200-d486-11e9-9cf3-3dabd51ada3d.png)

Navisworks is kinda backwards about creating custom tabs. The best example on how to do it is probably the old CASE bcf plugin:

https://github.com/johnpierson/case-apps/blob/9c768658f1224a5ccd69ea06c5532ba05f4eeb6f/2015/Case.Navis2BCF/Case.Navis2BCF/CASERibbon.cs#L14

The command class needs to inherit from `CommandHandlerPlugin` instead of `AddInPlugin` and you need to create a special ribbon layout xml that you feed in as an argument. It should look like this one:

https://github.com/johnpierson/case-apps/blob/9c768658f1224a5ccd69ea06c5532ba05f4eeb6f/2015/Case.Navis2BCF/Case.Navis2BCF/CustomRibbon.xaml

**Comment by pabloderen** [comment]
Try finding the dump file created by Navisworks and debug it with Visual
Studio.

You can access the actual exception message there.

**Comment by MM-SalvoDragotta** [comment]
> Try finding the dump file created by Navisworks and debug it with Visual
> Studio.
> 
> You can access the actual exception message there.
> …

Thanks! I got this msg

An unhandled exception of type 'System.IO.FileNotFoundException' occurred in Autodesk.Navisworks.Api.dll
Could not load file or assembly 'PythonConsoleControl, Version=2017.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

![image](https://user-images.githubusercontent.com/54158123/64738933-0b882c00-d534-11e9-823a-6503fd1e3eca.png)

**Comment by kristiansvenssonsweco** [comment]
I got something similar. I'm attaching my error dumps. I'm using the precompiled version from here:
https://github.com/dimven/NavisPythonShell/releases/download/2020.0.1/NavisPythonShell_2020.zip

[NavisPythonShell_2020_dump.zip](https://github.com/dimven/NavisPythonShell/files/3698073/NavisPythonShell_2020_dump.zip)

**Comment by dimven** [comment]
Did you download it from the releases? Is it possible the zip / dlls were blocked by windows? Try selecting Properties from the right-click menu on the zip before unpacking, or the dlls after unpacking, and check if there's an Unblock button/checkbox.

**Comment by kristiansvenssonsweco** [comment]
Yes, the zip is from the releases (2020.0.1). I unblocked the zip before unpacking. I have checked the plugin folder and the dll files have no unblock.

I'm using Navisworks 20
Version: 17.1.1338.62

**Comment by kristiansvenssonsweco** [comment]
I checked in Visual Studio and I got the same error as @MM-SalvoDragotta .

System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'NpsRuntime, Version=2017.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

I noticed it says **2017.0.0.0** while my Navisworks version is **17.1.1338.62**. Do you think this is the problem?

**Comment by dimven** [comment]
Not sure why that would be happening.

`NpsRuntime` is one of the dlls that gets compiled and referenced in the repo. Its version is hard-coded here:
![image](https://user-images.githubusercontent.com/7148394/66814093-b24e5680-ef3e-11e9-9594-f79674cd347d.png)

We're referencing it in the main NPS dll but it's reference without a specific version:
![image](https://user-images.githubusercontent.com/7148394/66814220-ea559980-ef3e-11e9-865d-75ff6733fc3d.png)

Is it possible you have an older version of `NpsRuntime.dll` stored somewhere that is somehow creating a conflict?

**Comment by kristiansvenssonsweco** [comment]
Thank you for trying to sort this out! The only NpsRuntime.dll is the one I first downloaded from your releases here:
https://github.com/dimven/NavisPythonShell/releases/download/2020.0.1/NavisPythonShell_2020.zip

Not sure what more to test!

**Comment by dimven** [comment]
Sorry I couldn't be of more help. Not sure either what else could be causing the dll to fail to load. Do you have any navisworks plugins installed? Maybe one of them is loading a different version of a dependent assembly?

**Comment by spencerzha0** [comment]
I've got the same issue when try to run RPW then NW will crashes.

**Comment by hoggs** [comment]
Hi! I've had the exact same issues as described above, and it was very frustrating. Anyway, after some digging I found that the problem (at least for me) is that the dependencies for the NPS plugin are not found when executing it. ref.: [Autodesk Forum](https://forums.autodesk.com/t5/navisworks-api/how-to-reference-other-dlls-into-my-plugin/td-p/3469122?profile.language=en)

I've currently installed NPS to "%Program Files%\Autodesk\Navisworks Manage 2020\Plugins" and not "%APPDATA%\Autodesk Navisworks Manage 2020\Plugins", but had the same issues with both locations.

So by copying the NPS dependencies to the "%Program Files%\Autodesk\Navisworks Manage 2020/Dependencies" directory - it now works!

**Comment by tomaszbielenin** [comment]
The way @hoggs described above worked perfectly for me e.i. only by extracting [NavisPythonShell_2020.zip](url=https://github.com/dimven/NavisPythonShell/releases/download/2020.0.1/NavisPythonShell_2020.zip) to "%Program Files%\Autodesk\Navisworks Manage 2020\Plugins" and then copying files directly to the "%Program Files%\Autodesk\Navisworks Manage 2020/Dependencies" allowed me to run NPS.
Thanks for sharing!

**Comment by dronov-dmitry** [comment]
> NPS dependencies

Hallo
I have the same problem
I copy [NavisPythonShell_2020.zip](https://github.com/dimven/NavisPythonShell/releases/download/2020.0.1/NavisPythonShell_2020.zip) to "%Program Files%\Autodesk\Navisworks Manage 2020\Plugin
But it still have problem
I copy NPS to  "%Program Files%\Autodesk\Navisworks Manage 2020/Dependencies"
But it still have problem
Can you help me please? What else problem can be?
How can i fix it?

**Comment by dronov-dmitry** [comment]
I found that crushed 
`typeof(NpsConfig)`

![image](https://github.com/dimven/NavisPythonShell/assets/9892891/05bc3ed7-f2e6-45b2-913c-405c60808f9f)

**Comment by GalAsor** [comment]
is it possible to run on navisowks 2025?

**Comment by hmzamz94-eng** [comment]
How can i run python script in Navisworks Manage 2025
