### ISSUE TITLE
text disappears from editor on first click after opening a script

### ISSUE THREAD

**Issue by sanzoghenzo** [dimven/NavisPythonShell#8]
Hi,
I'm glad you're keeping this project alive!

I just installed navisworks 2020 and your plugin, and it works like a charm... but I face a minor annoyance: after opening a script for the first time, the editor empties itself at the first click on it.

## steps to reproduce

1. Open Navisworks manage 2020
2. Open NPS
3. Click on the "Open Python Script" button
4. Select and open the script
5. Click anywhere in the editor panel
6. The text disappears/closes.
7. repeat steps 3 to 5
8. The text is still there and you can continue with the coding.

**Comment by dimven** [comment]
I remember that one:
https://github.com/architecture-building-systems/revitpythonshell/commit/eadf2356dfa62045b64e0e440a36bd53507ee6ff

I'll merge the fix here too.

**Comment by dimven** [comment]
6279d17f86920b4c847ee164e3f3ec842b27681e
